planning_pipelines:
  pipeline_names: ["ompl"]

plan_request_params:
  planner_id: ompl
  planning_attempts: 1
  planning_pipeline: ompl
  planning_time: 10.0
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0
  